<?php
/**
 * Created by Byteworks Limited.
 * Author: Chibuzor Ogbu
 * Date: 02/07/2017
 * Time: 4:44 PM
 */



// Retrieve order
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order = Mage::getModel('sales/order')->loadByIncrementId($orderId);

$i = 0;
$configFile = Mage::getConfig()->getModuleDir('etc', 'Payscrow_PayscrowGateway').DS.'config.xml';
$string = file_get_contents($configFile);
$xml = simplexml_load_string($string, 'Varien_Simplexml_Element');
$gatewayData = $xml->xpath( 'default/payment/payscrowgateway/gateway_url');
$gatewayUrl = $gatewayData[0];
$responseUrlData = $xml->xpath( 'default/payment/payscrowgateway/response_url');
$url = $responseUrlData[0];
$accessKeyData = $xml->xpath( 'default/payment/payscrowgateway/access_key');
$accessKey = $accessKeyData[0];
$deliveryDurationData = $xml->xpath( 'default/payment/payscrowgateway/max_delivery_duration');
$deliveryDuration = $deliveryDurationData[0];
$parseUrl = parse_url(trim($url));
$path = explode('/', $parseUrl['path'], 2);
$domain = trim(isset($parseUrl['host']) ? $parseUrl['host'] : array_shift($path));

if (!empty($domain)){
    $url = ( isset( $_SERVER[ 'HTTPS' ] ) && $_SERVER['HTTPS'] != 'off'
            ? "https"
            : "http" ) . "://" . ( ( isset( $_SERVER[ 'HTTP_HOST' ] ) && isset( $_SERVER[ 'SERVER_NAME' ] ) )
            ? ( str_ireplace( 'www.', '', $_SERVER[ 'SERVER_NAME' ] ) == str_ireplace(
                    'www.', '', $_SERVER[ 'HTTP_HOST' ]
                ) )
                ? $_SERVER[ 'HTTP_HOST' ]
                : $_SERVER[ 'SERVER_NAME' ]
            : $_SERVER[ 'SERVER_NAME' ] ).'/' . (isset($parseUrl['host']) ? $parseUrl['path'] : $path[0]);
    $responseUrl = $url;
}else{
    $url = ( isset( $_SERVER[ 'HTTPS' ] ) && $_SERVER['HTTPS'] != 'off'
            ? "https"
            : "http" ) . "://" . ( ( isset( $_SERVER[ 'HTTP_HOST' ] ) && isset( $_SERVER[ 'SERVER_NAME' ] ) )
            ? ( str_ireplace( 'www.', '', $_SERVER[ 'SERVER_NAME' ] ) == str_ireplace(
                    'www.', '', $_SERVER[ 'HTTP_HOST' ]
                ) )
                ? $_SERVER[ 'HTTP_HOST' ]
                : $_SERVER[ 'SERVER_NAME' ]
            : $_SERVER[ 'SERVER_NAME' ] ) . $url;
    $responseUrl = $url;
}

?>


<form name="payscrowform" id="payment_form_post?>" method="post" action="<?= $gatewayUrl?>">
    <input type="hidden" name="Ref" value="<?php echo $orderId; ?>">
    <input type="hidden" name="ResponseUrl" value="<?= $this->htmlEscape($responseUrl)?>">
    <input type="hidden" name="AccessKey" value="<?= $this->htmlEscape($accessKey)?>" />
    <input name="DeliveryDurationInDays" id="DeliveryDurationInDays" type="hidden" value="<?= $this->htmlEscape($deliveryDuration)?>" />

    <?php foreach($order->getAllVisibleItems() as $itemId => $item):?>

        <input type="hidden" name="Items[<?= $i ?>].Name" id="Items[<?= $i ?>]_Name"  value="<?= $this->htmlEscape($item->getName());?>" />
        <input type="hidden" name="Items[<?= $i ?>].Description" id="Items[<?= $i ?>]_Description"  value="<?= $this->htmlEscape($item->getProduct()->getDescription());?>" />
        <input type="hidden" name="Items[<?= $i ?>].Price" id="Items[<?= $i ?>]_Price"  value="<?= $this->htmlEscape(number_format($item->getPrice(),2));?>" />
        <input type="hidden" name="Items[<?= $i ?>].Quantity" id="Items[<?= $i ?>]_Quantity"  value="<?= $this->htmlEscape(number_format($item->getQtyOrdered(),0));?>" />
        <input type="hidden" name="Items[<?= $i ?>].Deliverable" id="Items[<?= $i ?>]_Deliverable"  value="<?=  $item->getIsVirtual() == 0 ? 'true': 'false';?>" />
        <input type="hidden" name="Items[<?= $i ?>].TaxAmount" id="Items[<?= $i ?>]_TaxAmount"  value="<?=  number_format($item->getTaxAmount(),2); ?>" />

    <?php $i++; endforeach;?>
    <input type="hidden" name="ShippingAmount" value="<?php echo number_format($order->getShippingAmount(),2); ?>">
    <input type="hidden" name="GrandTotal" value="<?php echo number_format($order->getBaseGrandTotal(),2); ?>">
</form>
<script type="text/javascript">
    document.payscrowform.submit();
</script>
